# Generated by Django 3.2 on 2021-05-02 10:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name of a beer type', max_length=200)),
                ('color', models.CharField(choices=[('d', 'dark'), ('l', 'light')], help_text='Choose dark or light type of a beer', max_length=1)),
                ('filtered', models.CharField(choices=[('y', 'filtered'), ('n', 'unfiltered')], help_text='Choose filtered or unfiltered', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='BeerReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular beer across whole review database', primary_key=True, serialize=False)),
                ('image', models.URLField(help_text='Enter URL for beer image', max_length=2000)),
                ('name', models.CharField(help_text='Enter beer name', max_length=200)),
                ('rating', models.CharField(choices=[('1', 'very bad'), ('2', 'bad'), ('3', 'average'), ('4', 'good'), ('5', 'perfect')], help_text='Choose beer rating', max_length=1)),
                ('comments', models.TextField(max_length=500)),
                ('date', models.DateField(auto_now_add=True)),
                ('beertype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diary.beertype')),
            ],
        ),
    ]
