# Generated by Django 3.2 on 2021-05-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_alter_beerreview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beerreview',
            name='image',
            field=models.URLField(default='', help_text='Enter URL for beer image', max_length=2000),
        ),
    ]
